import { GlobalStyle } from 'app/GlobalStyle';
import Header from 'components/Header';
import StyledComponentsRegistry from 'registry';
import { ThemeProvider } from 'styled-components';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const theme = {
  main: 'mediumseagreen'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}): React.ReactElement {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          <Header />
          <GlobalStyle />
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </ThemeProvider>
      </body>
    </html>
  );
}
